### ISSUE TITLE
Custom field sort. Multi-field sort

### ISSUE THREAD

**Issue by aditya7iyengar** [aditya7iyengar/rummage_ecto#41]

**Comment by thminhVN** [comment]
👍

**Comment by aditya7iyengar** [comment]
This will be tough to accomplish. Although there's a way around this using Rummage's query pipeline, which I have added in the documentation [here](https://github.com/aditya7iyengar/rummage_ecto/pull/56/files#diff-0763c3a57014e55e49ccb15062cfeabaR79) ....
