### ISSUE TITLE
Using rummage search with jsonb

### ISSUE THREAD

**Issue by callmeahab** [aditya7iyengar/rummage_ecto#49]
Can rummage be used to search through jsonb properties, in that case is there an example? Also some of the fields are optional and rummage (inheriting pg behavior I guess) throws an error when field doesn't exist, so is there a way to support optional fields?

Thanks

**Comment by yuchunc** [comment]
While it's possible with fragments, and building custom hooks, I don't think it is a good idea to search through jsonb. Here's a brief explaination on this topic: 
https://elixirforum.com/t/querying-embeds-many-field/2453/3?u=yuchunchttps://elixirforum.com/t/querying-embeds-many-field/2453/3?u=yuchunc

**Comment by callmeahab** [comment]
@yuchunc thanks for the recommendation. I'm not sure yet how to approach this issue, since I need to search through different types of objects that come from another database, and pg with jsonb seems to be the best solution, or rather the most flexible. I'm currently working with about 200 000 records in the database, and searching jsonb fields seems to be pretty fast. I realize that its a small dataset, and none of the jsonb properties is indexed yet (intentionally ofc)

**Comment by yuchunc** [comment]
Yeah... after digging in to Rummage, I think the out of box hooks can't handle embedded, you would probably need to write your own custom search hook. I moved my searches out of the embedded json, but for my sorting, I just wrote switch cases, each with instructions on what to sort by, using fragment. Here is some example:
```
  defp build_sort_query(queryable, %{by: field, direction: direction}) do
    case field do
      :inserted_at -> order_by(queryable, [{^direction, :inserted_at}])
      :start_date -> order_by(queryable, [{^direction, fragment("data -> 'start_date'")}])
      :annual_salary ->
        queryable
        |> group_by(:id)
        |> order_by([
            {^direction, fragment("data -> 'salary' -> 'currency'")},
            {^direction, fragment("AVG(((data -> 'salary' -> 'min' ->> 'amount')::NUMERIC + (data -> 'salary' -> 'max' ->> 'amount')::NUMERIC)/2)")}
           ])

  ...
```
It's a bit dirty but gets the job done. 😃
